### ISSUE TITLE
Build Issues (Ubuntu 18.04)

### ISSUE THREAD

**Issue by Hyjale** [Zee2/openwarp#3]
Hello Stranger,

Here are some things I had to-do for running your project on Ubuntu 18.04.
1. Use `git submodule update --init --recursive` instead of `git pull --recurse-submodules`
2. Replace instances of `filesystem` with `experimental/filesystem`

Thanks

**Comment by Zee2** [comment]
The issue with the `experimental/filesystem` is that older versions of GCC did not have C++'s standard filesystem library mainlined yet. Using GCC 8+ allows this to work. I'll add this to the README.

Unfortunately, changing it to `experimental` will break compatibility with other build platforms (clang, Windows, etc), so you just have to force a newer GCC.
